spring.application.name=server

## Open address IP cho phep truy cap thong qua IP host thay vi localhost (127.0.0.1)
#server.address=0.0.0.0
server.port=8080

## Cau hinh Database with POSTGRES
## =====================================================================================================================
## Su dung bien moi truong thay vi khai bao truc tiep gia truc tiep value trong file cau hinh application.properties.
## Cac buoc thuc hien dung bien cau hinh cho Spring Boot tren IDE IntelliJ nhu sau:
##
##      2. Tren IDE IntelliJ ngay Run -> Edit Configurations..
##      3. Sau khi click chon Edit Configurations.. -> popup hien thi -> ngay phan "Build and run" co dropdown "Modify options"
##         Click chon "Modify options" -> popup "Add run options" hien thi -> search environment variable -> click chon vao do.
##
##      4. Sau khi click chon environment variable -> IntelliJ tu dong them vao muc Edit Configurations.
##      5. Sau khi co muc environment variable, tai input them vao cac bien moi truong duoi dang KEY:VALUE.
##      6. Sau khi them bien moi truong trong IntelliJ, tai file application.properties khai bao ten bien moi truong cho
##         cho cac chuoi cau hinh cua Spring boot.
##
##   LUU Y:
##      Trong source nguon goc cua gamemini co file .env, file nay dung de cau hinh cho Docker, va docker se lay bien moi truong tu
##      file .env de doc thong tin. file .
##      Spring Boot khong doc bien moi truong tu file .env, tat ca bien moi truong Spring Boot lam viec thong qua viec cau hinh
##      nhu da mo ta o tren.
## =====================================================================================================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

## cau hinh hibernate DLL de hibernate tu dong tao cac table duoi DB thong qua mapping cac class POJO (tao DB bang Code First)
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=validate

## hien thi cau truy van
spring.jpa.show-sql=true

# Thay doi duong dan
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.disable-swagger-default-url=true

jwt.secretkey=${JWT_SECRET}
jwt.exp=${JWT_EXPIRE}


# ======================
# FLYWAY
# ======================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0
spring.flyway.validate-on-migrate=true
spring.flyway.clean-disabled=true

# ======================
# LOG
# ======================
logging.level.org.flywaydb=DEBUG